# 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# 2. Create a vector with values ranging from 10 to 49.

In [2]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
np.random.randint(0,8,(3,3))

array([[1, 2, 5],
       [6, 2, 4],
       [0, 7, 2]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
nums = np.array([1,2,0,0,4,0])

r = np.where(nums != 0)[0]
r

array([0, 1, 4], dtype=int64)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
x = np.random.randn(10,10)
print(np.min(x))
print(np.max(x))

-2.4282763099031834
2.1759775316032517


# 6. Create a random vector of size 30 and find the mean value.

In [6]:
x = np.random.random(30)
x.mean()


0.48913388758103554